version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: developmentpass
      MONGO_INITDB_DATABASE: fhir_demo
    ports:
      - "37017:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fhir_demo_net

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "38081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: developmentpass
      ME_CONFIG_MONGODB_URL: mongodb://root:developmentpass@mongo:27017/
    networks:
      - fhir_demo_net

networks:
  fhir_demo_net: